export const ActionTypes = {
       SET_PRODUCTS : 'SET_PRODUCTS',
       SELECTED_PRODUCTS : "SELECTED_PRODUCTS",
       REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
       INSERT_TO_CART:"INSERT_TO_CART",
       INCREASE_CART_COUNT:"INCREASE_CART_COUNT",
       DECREASE_CART_COUNT:" DECREASE_CART_COUNT",
};